Section "ServerFlags"
    Option "AutoAddGPU"    "false"
    Option "DontVTSwitch"  "true"
    Option "AllowEmptyInput" "true"
EndSection

Section "Device"
    Identifier  "card0"
    Driver      "modesetting"
    Option      "kmsdev"  "/dev/dri/card0"
EndSection

Section "Screen"
    Identifier  "screen0"
    Device      "card0"
EndSection
