case $- in
    *i*) ;;
    *) return ;;
esac

shopt -s checkwinsize histappend
HISTCONTROL=ignoredups:erasedups
HISTSIZE=1000
HISTFILESIZE=2000

printf '\033]0;Tunix Terminal\007'
# \$ is # for root and $ for everyone else, which is the whole point of it.
PS1='\[\033[1;36m\]\u@\h\[\033[0m\]:\[\033[1;34m\]\w\[\033[0m\]\$ '

alias ll='ls -alh'
