#!/usr/bin/env bash
set -euo pipefail

# Build gdk-pixbuf for Tunix, plus the shared libjpeg it decodes with.
#
# gdk-pixbuf is GTK's image loader: icons, stock images, anything a widget
# shows that started life as a PNG or JPEG goes through it. The image-codecs
# ports already build libjpeg-turbo, but into the *desktop* sysroot for the
# static tools; the GTK stack lives against the graphics sysroot, so a shared
# libjpeg is built here the same way libpng was built in the cairo chain.
#
# The loaders are compiled into the library (-Dbuiltin_loaders=all) rather
# than as modules. Module loaders need a loaders.cache generated by running
# gdk-pixbuf-query-loaders *on the target*, plus a well-known module
# directory; builtin loaders need nothing at runtime. For two formats the
# flexibility of modules buys nothing but a boot-time failure mode.
#
# gio_sniffing is off because it wants shared-mime-info's database, which is
# not shipped; gdk-pixbuf falls back to its own magic-number detection, which
# handles every format it can decode anyway.
#
# Output layout:
#   $OUT/graphics-sysroot/usr/{include,lib}   headers + .pc for gtk
#   $OUT/gdk-pixbuf-root/usr/lib              the shared libraries

PORT_NAME=gdk-pixbuf
ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT=${OUT:-$ROOT/ports/out}

# shellcheck source=ports/lib/cross-port.sh
source "$ROOT/ports/lib/cross-port.sh"

LIBJPEG_SOURCE="$ROOT/ports/src/libjpeg-turbo"
PIXBUF_SOURCE="$ROOT/ports/src/gdk-pixbuf"

BUILD="$OUT/gdk-pixbuf-build"
ROOT_DIR="$OUT/gdk-pixbuf-root"
CROSS_FILE="$OUT/tunix-meson-cross.ini"
CMAKE_FILE="$OUT/tunix-cmake-cross.cmake"

EXPECTED_VERSION=2.42.12

for source in "$LIBJPEG_SOURCE/CMakeLists.txt" "$PIXBUF_SOURCE/meson.build"; do
    [[ -f "$source" ]] || cross_port_fail \
        "missing $source; run git submodule update --init --recursive"
done

cross_port_require_toolchain
cross_port_require_tools meson ninja cmake pkg-config python3 "$READELF"

version=$(sed -n "s/^[[:space:]]*version[[:space:]]*:[[:space:]]*'\([0-9.]*\)'.*/\1/p" \
    "$PIXBUF_SOURCE/meson.build" | head -n1)
[[ "$version" == "$EXPECTED_VERSION" ]] || \
    cross_port_fail "expected gdk-pixbuf $EXPECTED_VERSION, found ${version:-unknown}"

for module in glib-2.0 gio-2.0 libpng; do
    [[ -f "$GRAPHICS_SYSROOT/usr/lib/pkgconfig/$module.pc" ]] || cross_port_fail \
        "$module is not in the graphics sysroot; build its port first"
done

rm -rf "$BUILD" "$ROOT_DIR"
mkdir -p "$BUILD" "$ROOT_DIR"

cross_port_write_meson_cross "$CROSS_FILE"
cross_port_write_cmake_toolchain "$CMAKE_FILE"
cross_port_export_pkg_config

# --- libjpeg-turbo (shared, for the graphics sysroot) --------------------
cmake -S "$LIBJPEG_SOURCE" -B "$BUILD/libjpeg" -G "Unix Makefiles" \
    -DCMAKE_TOOLCHAIN_FILE="$CMAKE_FILE" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_C_FLAGS="-O2 -fPIC" \
    -DENABLE_SHARED=ON -DENABLE_STATIC=OFF \
    -DWITH_TURBOJPEG=OFF -DWITH_SIMD=ON
cmake --build "$BUILD/libjpeg" --parallel "$JOBS"
DESTDIR="$GRAPHICS_SYSROOT" cmake --install "$BUILD/libjpeg"
DESTDIR="$ROOT_DIR" cmake --install "$BUILD/libjpeg"
[[ -f "$GRAPHICS_SYSROOT/usr/lib/pkgconfig/libjpeg.pc" ]] || \
    cross_port_fail "libjpeg.pc was not installed"

# --- gdk-pixbuf ----------------------------------------------------------
meson setup "$BUILD/gdk-pixbuf" "$PIXBUF_SOURCE" \
    --cross-file "$CROSS_FILE" \
    --prefix=/usr --libdir=lib --buildtype=release --default-library=shared \
    -Dpng=enabled \
    -Djpeg=enabled \
    -Dtiff=disabled \
    -Dgif=enabled \
    -Dothers=enabled \
    -Dbuiltin_loaders=all \
    -Dgio_sniffing=false \
    -Dintrospection=disabled \
    -Ddocs=false \
    -Dman=false \
    -Dtests=false \
    -Dinstalled_tests=false \
    -Drelocatable=false
meson compile -C "$BUILD/gdk-pixbuf" -j "$JOBS"
DESTDIR="$GRAPHICS_SYSROOT" meson install -C "$BUILD/gdk-pixbuf" --no-rebuild
DESTDIR="$ROOT_DIR" meson install -C "$BUILD/gdk-pixbuf" --no-rebuild

[[ -f "$GRAPHICS_SYSROOT/usr/lib/pkgconfig/gdk-pixbuf-2.0.pc" ]] || \
    cross_port_fail "gdk-pixbuf-2.0.pc was not installed into the graphics sysroot"

for spec in "libjpeg.so.62:libjpeg.so.62" \
            "libgdk_pixbuf-2.0.so.0:libgdk_pixbuf-2.0.so.0"; do
    name=${spec%%:*}
    soname=${spec##*:}
    library=$(find "$ROOT_DIR/usr/lib" -maxdepth 1 -type f -name "$name*" -print -quit)
    [[ -n "$library" ]] || cross_port_fail "$name was not installed"
    cross_port_check_library "$library" "$soname"
done

rm -rf "$ROOT_DIR/usr/include" "$ROOT_DIR/usr/lib/pkgconfig" \
       "$ROOT_DIR/usr/lib/cmake" "$ROOT_DIR/usr/bin" "$ROOT_DIR/usr/libexec" \
       "$ROOT_DIR/usr/share" "$ROOT_DIR/usr/lib/gdk-pixbuf-2.0"
find "$ROOT_DIR/usr/lib" -maxdepth 1 -name '*.a' -delete
find "$ROOT_DIR/usr/lib" -maxdepth 1 -type l -name '*.so' -delete

cross_port_finalize_root "$ROOT_DIR"
cross_port_check_runtime_closure "$ROOT_DIR" "$OUT/glib-root" "$OUT/cairo-root" \
    "$OUT/libffi-root" "$OUT/pixman-root"

size=$(du -sh "$ROOT_DIR" | cut -f1)
printf 'gdk-pixbuf %s (with shared libjpeg-turbo) staged at %s (%s)\n' \
    "$version" "$ROOT_DIR" "$size"
