#!/usr/bin/env python3
import argparse
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Rasterize a monospaced TrueType font into Tunix terminal glyph data."
    )
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--width", type=int, default=8)
    parser.add_argument("--height", type=int, default=18)
    parser.add_argument("--size", type=int, default=13)
    return parser.parse_args()


def glyph_repertoire() -> list[int]:
    codepoints = set(range(0x20, 0x7F))
    codepoints.update(range(0x00A0, 0x0180))
    codepoints.add(0x20AC)
    codepoints.update((0x2190, 0x2191, 0x2192, 0x2193))
    codepoints.update(range(0x2500, 0x2580))
    codepoints.update(range(0x2580, 0x25A0))
    codepoints.add(0xFFFD)
    return sorted(codepoints)


def write_wrapped_values(handle, values: list[str], indent: str = "    ", width: int = 96) -> None:
    line = indent
    for value in values:
        token = value + ","
        if len(line) + len(token) + 1 > width:
            handle.write(line.rstrip() + "\n")
            line = indent
        line += token + " "
    if line.strip():
        handle.write(line.rstrip() + "\n")


def main() -> None:
    args = parse_args()
    if args.width <= 0 or args.height <= 0 or args.size <= 0:
        raise SystemExit("width, height and size must be positive")
    if not args.source.is_file():
        raise SystemExit(f"font source not found: {args.source}")

    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError as exc:
        raise SystemExit("Pillow is required: python3 -m pip install Pillow") from exc

    font = ImageFont.truetype(str(args.source), args.size)
    ascent, _descent = font.getmetrics()
    baseline = min(ascent, args.height - 1)
    codepoints = glyph_repertoire()
    bitmaps: list[int] = []

    for codepoint in codepoints:
        character = chr(codepoint)
        image = Image.new("L", (args.width, args.height), 0)
        draw = ImageDraw.Draw(image)
        left, top, right, bottom = draw.textbbox(
            (0, baseline), character, font=font, anchor="ls"
        )
        glyph_width = right - left
        x = (args.width - glyph_width) // 2 - left
        draw.text((x, baseline), character, fill=255, font=font, anchor="ls")
        pixels = image.get_flattened_data() if hasattr(image, "get_flattened_data") else image.getdata()
        bitmaps.extend(pixels)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as output:
        output.write("/* Generated by scripts/generate-terminal-font.py. */\n")
        output.write(f"#define TUNIX_TERMINAL_FONT_GLYPH_COUNT {len(codepoints)}U\n\n")
        output.write(
            "static const uint32_t tunix_terminal_font_codepoints"
            "[TUNIX_TERMINAL_FONT_GLYPH_COUNT] = {\n"
        )
        write_wrapped_values(output, [f"UINT32_C(0x{value:04X})" for value in codepoints])
        output.write("};\n\n")
        output.write(
            "static const uint8_t tunix_terminal_font_alpha"
            "[TUNIX_TERMINAL_FONT_GLYPH_COUNT * TUNIX_TERMINAL_FONT_PIXELS_PER_GLYPH] = {\n"
        )
        write_wrapped_values(output, [f"0x{value:02X}" for value in bitmaps])
        output.write("};\n\n")
        output.write(
            "_Static_assert(sizeof(tunix_terminal_font_alpha) ==\n"
            "               TUNIX_TERMINAL_FONT_GLYPH_COUNT *\n"
            "               TUNIX_TERMINAL_FONT_PIXELS_PER_GLYPH,\n"
            "               \"terminal font alpha size mismatch\");\n"
        )

    print(
        f"terminal font: {args.output} "
        f"({len(codepoints)} glyphs, {args.width}x{args.height}, {len(bitmaps)} alpha bytes)"
    )


if __name__ == "__main__":
    main()
