# shellcheck shell=bash
# Shared setup for the ports that need the x86_64-linux-musl cross toolchain
# built by ports/build-musl-cross.sh -- currently libdrm and mesa.
#
# These differ from the musl-gcc ports in two ways that justify their own helper:
#
#   1. They are C++ (mesa mandates C++17), so they cannot use the musl-gcc
#      wrapper at all; they need the cross gcc with its musl-targeted libstdc++.
#   2. They are meson projects, so instead of a CMake toolchain file or plain
#      CC/CFLAGS they need a meson cross file.
#
# They also get their own sysroot, $OUT/graphics-sysroot, rather than reusing
# $OUT/desktop-sysroot.  The desktop sysroot is a copy of the musl-gcc sysroot
# and therefore carries a second set of libc headers and a second libc.so; if we
# put it on the cross compiler's include and library path those would shadow the
# cross toolchain's own musl.  Keeping the graphics libraries in a sysroot that
# holds *only* /usr/{include,lib} sidesteps that entirely -- libc comes from the
# cross toolchain, everything else from here.
#
# Required before sourcing:
#   ROOT - absolute path to the repository root.

: "${ROOT:?cross-port.sh: ROOT must be set before sourcing}"

OUT=${OUT:-$ROOT/ports/out}
JOBS=${JOBS:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 2)}

CROSS_TARGET=x86_64-linux-musl
CROSS_DIR="$OUT/musl-cross"
CROSS_SYSROOT="$CROSS_DIR/$CROSS_TARGET"
CROSS_CC="$CROSS_DIR/bin/$CROSS_TARGET-gcc"
CROSS_CXX="$CROSS_DIR/bin/$CROSS_TARGET-g++"
CROSS_AR="$CROSS_DIR/bin/$CROSS_TARGET-ar"
CROSS_STRIP="$CROSS_DIR/bin/$CROSS_TARGET-strip"
# musl's libc.so is itself the dynamic loader. The ld-musl-x86_64.so.1 symlink
# beside it is absolute (/lib/libc.so) and so resolves against the build host,
# not the sysroot -- use the real file.
CROSS_LOADER="$CROSS_SYSROOT/lib/libc.so"
GRAPHICS_SYSROOT="$OUT/graphics-sysroot"

READELF=${READELF:-readelf}

cross_port_fail() {
    echo "build-${PORT_NAME:-cross-port}: $*" >&2
    exit 1
}

cross_port_require_toolchain() {
    for tool in "$CROSS_CC" "$CROSS_CXX" "$CROSS_AR" "$CROSS_STRIP"; do
        [[ -x "$tool" ]] || cross_port_fail \
            "the musl cross toolchain is missing ($tool); run ports/build-musl-cross.sh first"
    done
    [[ -f "$CROSS_LOADER" ]] || cross_port_fail "the target musl loader is missing from $CROSS_SYSROOT"
    # Not linux/drm.h: the DRM UAPI headers install to /usr/include/drm, and on
    # most distributions they come from libdrm rather than the kernel headers
    # package. libdrm carries its own copies anyway, so what we actually need
    # from the host is the rest of the UAPI -- linux/dma-buf.h, linux/sync_file.h
    # and friends, which mesa's winsys code includes.
    [[ -f "$CROSS_SYSROOT/include/linux/dma-buf.h" ]] || cross_port_fail \
        "the cross sysroot has no Linux UAPI headers; re-run ports/build-musl-cross.sh"
}

cross_port_require_tools() {
    local tool
    for tool in "$@"; do
        command -v "$tool" >/dev/null 2>&1 || cross_port_fail "$tool was not found"
    done
}

# Mesa generates a lot of its source with Python + Mako templates. Fail with an
# actionable message rather than letting meson report a confusing import error
# halfway through configuration.
cross_port_require_python_module() {
    local module="$1" hint="$2"
    python3 -c "import $module" >/dev/null 2>&1 || cross_port_fail \
        "the python3 module '$module' is required (install it, e.g. $hint)"
}

# Write a meson cross file describing the Tunix target.
#   cross_port_write_meson_cross <path>
cross_port_write_meson_cross() {
    local path="$1"
    mkdir -p "$(dirname "$path")"
    cat > "$path" <<EOF_CROSS
# Generated by ports/lib/cross-port.sh -- do not edit.
[binaries]
c = '$CROSS_CC'
cpp = '$CROSS_CXX'
ar = '$CROSS_AR'
strip = '$CROSS_STRIP'
pkg-config = 'pkg-config'
# Tunix runs the same x86_64 Linux syscall ABI as the build host, so a target
# binary executes here once the target loader is handed the target libraries.
# Giving meson a working exe wrapper lets its run-time checks actually run
# instead of falling back to guessed cross values.
exe_wrapper = ['$CROSS_LOADER', '--library-path', '$CROSS_SYSROOT/lib:$GRAPHICS_SYSROOT/usr/lib']

[built-in options]
c_args = ['-O2', '-fPIC', '-I$GRAPHICS_SYSROOT/usr/include']
cpp_args = ['-O2', '-fPIC', '-I$GRAPHICS_SYSROOT/usr/include']
c_link_args = ['-L$GRAPHICS_SYSROOT/usr/lib', '-Wl,-rpath-link,$GRAPHICS_SYSROOT/usr/lib']
cpp_link_args = ['-L$GRAPHICS_SYSROOT/usr/lib', '-Wl,-rpath-link,$GRAPHICS_SYSROOT/usr/lib']

[properties]
# Without this meson notices build and host are both linux/x86_64 and runs
# run-checks *directly*, skipping the exe_wrapper -- and a musl binary run on
# the glibc host dies with ENOENT for its missing /lib/ld-musl loader, which
# meson's log then reports as the check binary itself not existing. glib is
# where this finally bit: its gnulib probes are run checks, and every one of
# them "DID NOT COMPILE" until the wrapper was actually used.
needs_exe_wrapper = true

# meson uses both of these for pkg-config on the *host* machine only: the search
# path, and PKG_CONFIG_SYSROOT_DIR to rewrite the -I/-L prefixes in .pc files
# that were installed with prefix=/usr. Setting them here rather than exporting
# them into the environment matters, because an exported PKG_CONFIG_LIBDIR also
# hijacks meson's native lookups -- which is how a cross build ends up unable to
# find a build-time tool like wayland-scanner that is installed on the host.
#
# sys_root only feeds pkg-config; the cross gcc keeps using its own sysroot for
# libc, which is why the compiler search paths stay untouched.
#
# Both pkgconfig directories are listed: architecture-independent packages put
# their .pc in share/pkgconfig, and wayland-protocols is one of them.
sys_root = '$GRAPHICS_SYSROOT'
pkg_config_libdir = ['$GRAPHICS_SYSROOT/usr/lib/pkgconfig', '$GRAPHICS_SYSROOT/usr/share/pkgconfig']

[host_machine]
system = 'linux'
kernel = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
EOF_CROSS
}

# The CMake equivalent of the meson cross file, for the ports that build with
# CMake rather than meson (libpng).
#   cross_port_write_cmake_toolchain <path>
cross_port_write_cmake_toolchain() {
    local path="$1"
    mkdir -p "$(dirname "$path")"
    cat > "$path" <<EOF_TOOLCHAIN
# Generated by ports/lib/cross-port.sh -- do not edit.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER "$CROSS_CC")
set(CMAKE_CXX_COMPILER "$CROSS_CXX")
set(CMAKE_AR "$CROSS_AR")
set(CMAKE_FIND_ROOT_PATH "$GRAPHICS_SYSROOT/usr")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
# Link tests would need to run a target binary; compiling one is proof enough.
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
EOF_TOOLCHAIN
}

# Where the graphics sysroot lives is described to meson by the cross file, per
# machine. The environment must stay clear of pkg-config overrides, because
# those apply to *both* machines: a PKG_CONFIG_LIBDIR pointing at the target
# sysroot makes meson unable to find build-time tools installed on the host.
cross_port_export_pkg_config() {
    unset PKG_CONFIG_LIBDIR
    unset PKG_CONFIG_SYSROOT_DIR
    unset PKG_CONFIG_PATH
}

# Assert a shared object we built is actually a target object with a SONAME,
# and that it did not accidentally pick up a host dependency.
#   cross_port_check_library <path> <expected-soname>
cross_port_check_library() {
    local library="$1" expected="$2"
    [[ -f "$library" ]] || cross_port_fail "$library was not built"
    local soname
    soname=$("$READELF" -d "$library" | sed -n 's/.*SONAME.*\[\([^]]*\)\].*/\1/p')
    [[ "$soname" == "$expected" ]] || \
        cross_port_fail "$(basename "$library") has SONAME '${soname:-none}', expected '$expected'"
    if "$READELF" -d "$library" | grep -qE 'Shared library: \[(libc\.so\.6|ld-linux)'; then
        cross_port_fail "$(basename "$library") links against the host glibc"
    fi
}

# Stage the C++ runtime into a library directory that is going into the image.
#
# libstdc++ and the gcc unwinder belong to the toolchain rather than to any one
# port, but nothing else in the image is C++, so whichever port drags them in
# has to ship them. Without this a C++ library loads far enough to start
# relocating and then dies on __gxx_personality_v0 and the __cxxabiv1 vtables.
#   cross_port_stage_cxx_runtime <libdir>
cross_port_stage_cxx_runtime() {
    local libdir="$1"
    mkdir -p "$libdir"
    local soname real
    for soname in libstdc++.so.6 libgcc_s.so.1; do
        [[ -e "$CROSS_SYSROOT/lib/$soname" ]] || \
            cross_port_fail "$soname is missing from the cross sysroot"
        # libstdc++.so.6 is a symlink to libstdc++.so.6.0.NN; libgcc_s.so.1 is a
        # real file. Copy the target under its real name and recreate the
        # SONAME link, so the image matches what the linker recorded.
        real=$(basename "$(readlink -f "$CROSS_SYSROOT/lib/$soname")")
        cp -L "$CROSS_SYSROOT/lib/$soname" "$libdir/$real"
        chmod 0755 "$libdir/$real"
        [[ "$real" == "$soname" ]] || ln -sfn "$real" "$libdir/$soname"
    done
}

# Assert that every NEEDED entry of every shared object we are about to ship is
# satisfied by something else being shipped.
#
# This is deliberately a static check rather than "the demo ran". The host probe
# runs with the cross toolchain's library directory on the loader path, so a
# runtime library we forgot to stage still resolves there and the failure only
# shows up after boot -- which is exactly how the missing libstdc++ was missed
# the first time.
#   cross_port_check_runtime_closure <root> [root...]
cross_port_check_runtime_closure() {
    local -a roots=("$@")
    # libc.so is provided by the shared musl runtime port, not by these roots.
    local provided=$'libc.so\n'
    local root file need

    for root in "${roots[@]}"; do
        while read -r file; do
            provided+="$(basename "$file")"$'\n'
        done < <(find "$root" -name '*.so*')
    done

    for root in "${roots[@]}"; do
        while read -r file; do
            while read -r need; do
                [[ -n "$need" ]] || continue
                grep -Fxq "$need" <<<"$provided" || cross_port_fail \
                    "$(basename "$file") needs $need, which nothing in the image provides"
            done < <("$READELF" -d "$file" | \
                sed -n 's/.*Shared library: \[\([^]]*\)\].*/\1/p')
        done < <(find "$root" -type f -name '*.so*')
    done
}

# Strip and normalise permissions on everything staged for the image.
cross_port_finalize_root() {
    local root="$1"
    find "$root" -type f -name '*.so*' ! -type l \
        -exec "$CROSS_STRIP" --strip-unneeded {} + 2>/dev/null || true
    find "$root" -type f -name '*.so*' ! -type l -exec chmod 0755 {} + 2>/dev/null || true
    # Documentation and pkg-config data are build-time artefacts; the image only
    # needs the libraries themselves.
    rm -rf "$root/usr/share/man" "$root/usr/share/doc" 2>/dev/null || true
}
